### ISSUE TITLE
Allow users pass in custom formatting & add-on validation logic

### ISSUE THREAD

**Issue by abayomi1196** [abayomi1196/react-creditcard-validator#9]
This lets end-users, pass in additional validation logic, or their own formatting patterns.
This helps us cover card types that may not be covered in our current codebase, and provides value to users seeking more control over validation & formatting

**Comment by JCalmCrasher** [comment]
Don't you think it would be better to incrementally add support for other card types? Giving users the freedom to pass in their own _logic_ might not correspond to existing card standards.

**Comment by abayomi1196** [comment]
the logic will definitely be constrained and limited na..something like
- total cardNumber length,
- cardNumber formatting type i.e 4, 6, 3 etc

so that either way, it can be handled by our own logic
